Feat pimoroni boards
amperka/hardware-drawings pull request #121
Opened 2020-12-21 20:08 UTC by alinkacxt

- Kitty Case for micro:bit
- Drive:Bit
- Servo: Bit 
- Moisture Sensor for micro:bit
- Ultrasonic Distance Sensor Breakout
- BitFace Robot Face Breakout
- Kitronik ZIP Tile for micro:bit.

2020-12-22 10:03 UTC, AlexErAmp requested changes
Слово Kittenbot по моему здесь не по центру расположено. И хотелось бы, чтобы его было получше видно.

![kittenbot](https://user-images.githubusercontent.com/43956118/102876074-c8ff1000-4455-11eb-8bcf-60196dab296a.png)

2020-12-22 18:30 UTC, alinkacxt commented
Шрифт увеличила и по центру расположила.

2020-12-23 09:28 UTC, AlexErAmp approved these changes
LGTM

2020-12-23 09:46 UTC, alinkacxt commented
😊

2020-12-23 09:46 UTC, merged